### ISSUE TITLE
Intermittent NullReferenceException when recording visits

### ISSUE THREAD

**Issue by parekhkb** [SteveGilham/altcover#71] opened 2019-09-09 03:22 UTC
First, let me say I'm enjoying using AltCover. It's by far the most feature rich code coverage tool for dotnet core that I've used so far. 

I've run into an intermittent failure that I can't explain. I get random tests that fail with the following stack trace:

```
 Error Message:
   System.NullReferenceException : Object reference not set to an instance of an object.
  Stack Trace:
     at System.Collections.Generic.Dictionary`2.FindEntry(TKey key)
   at AltCover.Recorder.Counter.EnsureModule(Dictionary`2 counts, String moduleId)
   at AltCover.Recorder.Counter.AddSingleVisit(Dictionary`2 counts, String moduleId, Int32 hitPointId, Track context)
   at AltCover.Recorder.Instance.VisitImpl@230.Invoke(String moduleId, Int32 hitPointId, Track context)
   at AltCover.Recorder.Instance.VisitImpl(String moduleId, Int32 hitPointId, Track context)
```

It's never the same test case, and on retry the test passes. 

I didn't find this in your list of known intermittent failures.

**Comment by SteveGilham** [comment] 2019-09-09 08:22
That list of known intermittent issues is aimed at people building the code, rather than using it.

When AltCover instruments an assembly, it puts a number of function calls of the form `Visit(line, assembly)` into the code.  The failure you are seeing indicates that somehow the `assembly` identifier, which should be a constant and non-empty string, is being received as null; but there isn't any obvious mechanism for that to happen.

Without an example that might reproduce the issue, the best I'm going to be able to do here is simply filter when that happens.

**Comment by parekhkb** [comment] 2019-09-09 22:48
Thanks. 
If you filter when that happens, won't that cause code coverage totals to be misrepresented? 

I'll think about how I might provide a repo to you.

**Comment by SteveGilham** [comment] 2019-09-10 07:36
Yes, whatever those hits were would be discarded; but then where the hits were has already been corrupted somehow.

**Comment by parekhkb** [comment] 2019-09-10 14:46
Wouldn’t such a change obfuscate the issue and make the root cause harder to track down? It makes the coverage results less reliable.

Also, I am adding Exclude filter for assembly as well as filter for type regexes. Could those regency be causing these problems. Are you excluding those assemblies from the dictionary, but then they are accidentally being instrumented anyways?

**Comment by SteveGilham** [comment] 2019-09-10 15:13
Filtering is an excluding operation : if an item's name successfully matches a regex for the appropriate class of thing, it should be omitted from instrumentation.  Assemblies that aren't instrumented (ones marked by AssemblyExcludeFilter) may have their assembly references and strong-names rewritten, but should not have any visit instrumentation added.

The as-released recorder has no exception handling above the point where the stack trace was cut off in the original report, so you should be able to see from the full stack which method in which of your assemblies is making the failing call (and whether it's one that wasn't expected to be instrumented).

_If there's a Visit call from an unexpected assembly, then please submit a new issue regarding filtering._

Even if an assembly gets wrongly instrumented, the module identifier (either the `MvId` for the NCover style output, or the file SHA-1 hash for OpenCover) should still never be null, as it is in the call that led to the stack trace above.

The attached -- [altcover.inspector.zip](https://github.com/SteveGilham/altcover/files/3596223/altcover.inspector.zip) --  is a simple program to scan instrumented assemblies and look for code that might cause problems like you are seeing.  It locates calls to the recorder method, and checks that

- plausible arguments have been put on the stack
- that there are no suspicious jumps into the middle of the injected code (though I would expect those to cause a malformed program exception due to stack imbalance instead)

dumping any problems found to stderr.

Supplied as project and source so it can be inspected before doing a `dotnet run` over possibly sensitive code.

This should help determine if it's occasional static corruption within the build and test pipeline; runtime corruption (stack crashing and the like) would be something else altogether.

**Comment by parekhkb** [comment] 2019-09-10 18:36
>If there's a Visit call from an unexpected assembly, then please submit a new issue regarding filtering.

Thanks, further up the call stack I am NOT seeing excluded assemblies. They look to be assemblies that are correct to be included in coverage. So doesn't appear to be an issue with the filtering. 

I will try to use the inspector you provided. Since I am using `dotnet test` in the "Instrument now and run tests now" mode, should I run your inspector after running tests with coverage?

**Comment by SteveGilham** [comment] 2019-09-11 07:49
As you have `/p:AltCoverFailFast=true`, then when `dotnet test` fails, no further AltCover operations are performed.  In particular, no tidying up is done; the as-built files in the test project will remain in `$(TargetDir)__Saved` and the instrumented ones in `$(TargetDir)` where you can scan them.

So, when you get test failure due to such an exception, everything should be there for you to inspect; either in `$(TargetDir)` for the project being run under `dotnet test` or the ones instrumented in-place for the background worker.

**Comment by SteveGilham** [comment] 2019-09-18 11:10
Did you get any results from the scan, or any repro?

**Comment by parekhkb** [comment] 2019-09-19 00:44
I tried a several runs locally but wasn't able to get a local repo. I will try to set up a continuous loop tonight and see if I can get a failure in the morning.

We are still seeing this issue in our CI pipeline intermittently, and every time rerunning it is successful.

Also, side note: running dotnet build on your fsharp project caused dotnet cli to act very strangely with CSharp projects. I had to uninstall and reinstall the dotnet sdk to get it to work again. It kept adding FSharp.Core to my deps.json and then erroring out during runtime due to unresolved assembly. Any ideas on that?

**Comment by SteveGilham** [comment] 2019-09-19 07:45
I have no idea what's happening there, I'm afraid.

**Comment by SteveGilham** [comment] 2019-09-19 15:02
Here's the inspector code rewritten in C#, which may help -- 
[altcover.inspector.zip](https://github.com/SteveGilham/altcover/files/3631919/altcover.inspector.zip)

**Comment by parekhkb** [comment] 2019-10-12 00:38
Ok, finally had time to spend on this. I was able to have a private branch on my CI upload the build netcoreapp2.2 folder from a failing unittest project. Once I had a repro of the AltCover NullReference failure I downloaded that artifact and ran your inspector on all my dlls (both test and app code) in the folder.

It seems the inspector didn't find any issues:

```
/usr/local/share/dotnet/dotnet "/Users/parekhkb/Downloads/altcover.inspector (1)/bin/Debug/netcoreapp2.1/altcover.inspector.dll" /Users/parekhkb/Downloads/altcover_failure/UnitTests/Core.Test/bin/Release/netcoreapp2.2/MyApp.Admin.Core.dll /Users/parekhkb/Downloads/altcover_failure/UnitTests/Core.Test/bin/Release/netcoreapp2.2/MyApp.Admin.Data.dll /Users/parekhkb/Downloads/altcover_failure/UnitTests/Core.Test/bin/Release/netcoreapp2.2/MyApp.Core.Test.dll /Users/parekhkb/Downloads/altcover_failure/UnitTests/Core.Test/bin/Release/netcoreapp2.2/MyApp.Core.dll /Users/parekhkb/Downloads/altcover_failure/UnitTests/Core.Test/bin/Release/netcoreapp2.2/MyApp.Data.Common.dll /Users/parekhkb/Downloads/altcover_failure/UnitTests/Core.Test/bin/Release/netcoreapp2.2/MyApp.Data.Database.Identity.dll /Users/parekhkb/Downloads/altcover_failure/UnitTests/Core.Test/bin/Release/netcoreapp2.2/MyApp.Data.Database.Master.dll /Users/parekhkb/Downloads/altcover_failure/UnitTests/Core.Test/bin/Release/netcoreapp2.2/MyApp.Data.Database.Private.dll /Users/parekhkb/Downloads/altcover_failure/UnitTests/Core.Test/bin/Release/netcoreapp2.2/MyApp.Data.Database.Public.dll /Users/parekhkb/Downloads/altcover_failure/UnitTests/Core.Test/bin/Release/netcoreapp2.2/MyApp.Data.Entities.dll /Users/parekhkb/Downloads/altcover_failure/UnitTests/Core.Test/bin/Release/netcoreapp2.2/MyApp.Data.Models.dll /Users/parekhkb/Downloads/altcover_failure/UnitTests/Core.Test/bin/Release/netcoreapp2.2/MyApp.Data.Repository.dll /Users/parekhkb/Downloads/altcover_failure/UnitTests/Core.Test/bin/Release/netcoreapp2.2/MyApp.DataSync.Common.dll /Users/parekhkb/Downloads/altcover_failure/UnitTests/Core.Test/bin/Release/netcoreapp2.2/MyApp.Database.Shared.dll /Users/parekhkb/Downloads/altcover_failure/UnitTests/Core.Test/bin/Release/netcoreapp2.2/MyApp.Deployment.Engine.dll /Users/parekhkb/Downloads/altcover_failure/UnitTests/Core.Test/bin/Release/netcoreapp2.2/MyApp.Grpc.Common.dll /Users/parekhkb/Downloads/altcover_failure/UnitTests/Core.Test/bin/Release/netcoreapp2.2/MyApp.Identity.Core.dll /Users/parekhkb/Downloads/altcover_failure/UnitTests/Core.Test/bin/Release/netcoreapp2.2/MyApp.Rolodex.Core.dll /Users/parekhkb/Downloads/altcover_failure/UnitTests/Core.Test/bin/Release/netcoreapp2.2/MyApp.Rolodex.Data.dll /Users/parekhkb/Downloads/altcover_failure/UnitTests/Core.Test/bin/Release/netcoreapp2.2/MyApp.Rolodex.GrpcMapping.dll /Users/parekhkb/Downloads/altcover_failure/UnitTests/Core.Test/bin/Release/netcoreapp2.2/MyApp.Test.Common.dll /Users/parekhkb/Downloads/altcover_failure/UnitTests/Core.Test/bin/Release/netcoreapp2.2/MyApp.Tools.EmailTools.dll /Users/parekhkb/Downloads/altcover_failure/UnitTests/Core.Test/bin/Release/netcoreapp2.2/MyApp.Tools.Excel.dll /Users/parekhkb/Downloads/altcover_failure/UnitTests/Core.Test/bin/Release/netcoreapp2.2/MyApp.Worker.Common.dll
Scan completed for MyApp.Admin.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Scan completed for MyApp.Admin.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Scan completed for MyApp.Core.Test, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Scan completed for MyApp.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Scan completed for MyApp.Data.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Scan completed for MyApp.Data.Database.Identity, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Scan completed for MyApp.Data.Database.Master, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Scan completed for MyApp.Data.Database.Private, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Scan completed for MyApp.Data.Database.Public, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Scan completed for MyApp.Data.Entities, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Scan completed for MyApp.Data.Models, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Scan completed for MyApp.Data.Repository, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Scan completed for MyApp.DataSync.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Scan completed for MyApp.Database.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Scan completed for MyApp.Deployment.Engine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Scan completed for MyApp.Grpc.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Scan completed for MyApp.Identity.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Scan completed for MyApp.Rolodex.Core, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Scan completed for MyApp.Rolodex.Data, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Scan completed for MyApp.Rolodex.GrpcMapping, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Scan completed for MyApp.Test.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Scan completed for MyApp.Tools.EmailTools, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Scan completed for MyApp.Tools.Excel, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
Scan completed for MyApp.Worker.Common, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

Process finished with exit code 0.
```

**Comment by SteveGilham** [comment] 2019-10-20 09:39
So, if the instrumented IL is consistent, and doesn't contain any nulls, as shown, executing it should not cause any NRE failures.  As this only seems to happen on your build server, it looks like something environmental and specific to that machine.

I think I'm just going to have to close this as "can't fix", having made the necessary mitigation to ignore such events should they arise.

**Comment by parekhkb** [comment] 2019-10-23 18:34
@SteveGilham I upgraded to 6.2.727. And it seemed to fix our issue. But we just had another repro in our build CI:

It Seems your WorkAround to ignore the error isn't working.

```System.TypeInitializationException : The type initializer for 'MyApp.Services.Test.ServicesTestBase' threw an exception.
---- System.Collections.Generic.KeyNotFoundException : The given key '38-C4-21-D3-93-43-5F-58-D4-35-DF-48-3D-BD-F5-B2-A4-A5-E3-E2' was not present in the dictionary.
  Stack Trace:
     at MyApp.Services.Test.CalendarServiceTests.TestSetup() in /opt/atlassian/pipelines/agent/build/test/UnitTests/Services.Test/CalendarServiceTests.cs:line 82
----- Inner Stack Trace -----
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at AltCover.Recorder.Counter.AddSingleVisit(Dictionary`2 counts, String moduleId, Int32 hitPointId, Track context)
   at AltCover.Recorder.Instance.VisitImpl@222.Invoke(String moduleId, Int32 hitPointId, Track context)
   at AltCover.Recorder.Instance.VisitImpl(String moduleId, Int32 hitPointId, Track context)
   at MyApp.Core.Models.AutoMapper.PatchModelAutoMapperExtensions.<>c.<UsePatchModels>b__0_2(PropertyMap pm) in /opt/atlassian/pipelines/agent/build/src/Common/Core/Models/AutoMapper/PatchModelAutoMapperExtensions.cs:line 23
   at AutoMapper.Profile.<>c__DisplayClass76_0.<ForAllPropertyMaps>b__0(PropertyMap pm, IMemberConfigurationExpression cfg) in C:\projects\automapper\src\AutoMapper\Profile.cs:line 94
   at AutoMapper.ProfileMap.Configure(TypeMap typeMap, IConfigurationProvider configurationProvider) in C:\projects\automapper\src\AutoMapper\ProfileMap.cs:line 153
   at AutoMapper.ProfileMap.Configure(IConfigurationProvider configurationProvider) in C:\projects\automapper\src\AutoMapper\ProfileMap.cs:line 112
   at AutoMapper.MapperConfiguration.Seal() in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 314
   at AutoMapper.MapperConfiguration..ctor(MapperConfigurationExpression configurationExpression) in C:\projects\automapper\src\AutoMapper\MapperConfiguration.cs:line 56
   at AutoMapper.ServiceCollectionExtensions.<>c__DisplayClass11_0.<AddAutoMapperClasses>b__4(IServiceProvider sp) in C:\projects\automapper-extensions-microsoft-dependencyinjectio\src\AutoMapper.Extensions.Microsoft.DependencyInjection\ServiceCollectionExtensions.cs:line 97
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScoped(ScopedCallSite scopedCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at AutoMapper.ServiceCollectionExtensions.<>c.<AddAutoMapperClasses>b__11_5(IServiceProvider sp) in C:\projects\automapper-extensions-microsoft-dependencyinjectio\src\AutoMapper.Extensions.Microsoft.DependencyInjection\ServiceCollectionExtensions.cs:line 99
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitTransient(TransientCallSite transientCallSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at MyApp.Test.Common.AutoMapperHelper.CreateMapper(IEnumerable`1 profileTypes) in /opt/atlassian/pipelines/agent/build/test/Common/AutoMapperHelper.cs:line 30
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at MyApp.Services.Test.ServicesTestBase..cctor() in /opt/atlassian/pipelines/agent/build/test/UnitTests/Services.Test/ServicesTestBase.cs:line 9```

**Comment by SteveGilham** [comment] 2019-10-23 18:53
The work-round was for an exception from a null key.  This one is different -- the key actually has a value.

**Comment by SteveGilham** [comment] 2019-10-24 08:56
There is a very narrow window for a race condition that could possibly cause this if you are running under an explicit  `AltCover`  + `AltCover Runner` and are using the control file option to toggle collection, with a multi-threaded application, in which the key could have been added to the in-memory store and then, before being used, all the data are flushed to the recording file in a second thread.

So I shall add this to the trap and carry on, in the expectation that it affects at most one visit per thread just as recording is being toggled.

However, given the original report, for which there is no static code path, and given that the problem seems to be localized to just your build server out of all contexts, I suspect there is some thing specific to that environment.  The behaviour is like the module key argument is not being set/updated before it's used; so starting with a default null, and then possibly next time around having a value, being set as a key in the dictionary and then updated.

**Comment by SteveGilham** [comment] 2019-10-25 18:00
If you want to try it, there's a pre-release build (v6.3.731-pre) with more mitigation and logging [on the AppVeyor CI server](https://ci.appveyor.com/project/SteveGilham/altcover/build/artifacts) -- main package [here](https://ci.appveyor.com/api/buildjobs/bhc33hl2dk4rs69n/artifacts/_Packaging%2Faltcover.6.3.731-pre.nupkg).

This will trap and log exceptions reported in Issue #71 as files `<coverage report path>.<timestamp>.exn`; the first few lines indicate what was being logged and what went wrong, followed by a full stack trace of the fault.

**Comment by parekhkb** [comment] 2019-10-29 18:35
We are not using Altcover + Altcover runner. We are using the dotnet options 
```
dotnet test -c release /p:AltCover=true /p:AltCoverForce=true /p:AltCoverAssemblyExcludeFilter='^((?!(Cmg))||(?=(Cmg\..*Test.*))).*$' /p:AltCoverTypeFilter='^Cmg\..*(?=(\.Migrations\.))(?!(\.Migrations\..*Custom\.)).*$' /p:AltCoverFailFast=true
```
Mine app is mutlithreaded hence the ConcurrentDictionary for thread safety in the stack above. I think your theory about a race condition in setting and using the key sounds like the right direction.

**Comment by SteveGilham** [comment] 2019-10-29 19:05
The important bit is the using [the control file option to toggle collection](https://github.com/SteveGilham/altcover/wiki/Pause%E2%95%B1Resume-and-the-Control-File), which is more suited to operational testing, starting collection only when ready to run an interesting operation, and pausing thereafter; while the same stages happen in the `dotnet test` operation as in the explicit use of AltCover as a tool, those stages are rather more opaque, and in a unit-test context, it's less plausible to want to exclude part of the process.

So direct question -- do you toggle collection with the control file?

Additionally, any race (key added on thread 1, removed on thread 2, then used on thread 1) still would not explain the initial report concerning null keys on your build server.

Second direct question -- have you ever observed that behaviour on any other host?

And finally -- have you tried the interim release v6.3.731-pre, and if so, do you have any of the .exn files?

**Comment by SteveGilham** [comment] 2019-10-31 16:33
[Release 6.4.734](https://www.nuget.org/packages/AltCover/6.4.734) has the exception logging; also, the behaviour at the point when recording is paused has been adjusted to remove the narrow race condition window.

**Closed** 2019-11-11 08:38 UTC
Labels: bug, cannot repro, ready to close
