### ISSUE TITLE
UWP program instrumentation phase fails

### ISSUE THREAD

**Issue by robvdnieuw** [SteveGilham/altcover#187] opened 2023-06-22 09:18 UTC
We have a project that depends on a UWP winmd file. 

<Reference Include="Windows.Foundation.FoundationContract">
            <HintPath>C:\Program Files (x86)\Windows Kits\10\References\10.0.22000.0\Windows.Foundation.FoundationContract\4.0.0.0\Windows.Foundation.FoundationContract.winmd</HintPath>
            <IsWinMDFile>true</IsWinMDFile>
        </Reference>
        <Reference Include="Windows.Foundation.UniversalApiContract">
            <HintPath>C:\Program Files (x86)\Windows Kits\10\References\10.0.22000.0\Windows.Foundation.UniversalApiContract\14.0.0.0\Windows.Foundation.UniversalApiContract.winmd</HintPath>
            <IsWinMDFile>true</IsWinMDFile>
        </Reference>

It builds ok. 

During instrumentation we get the error following error. 

Failed to resolve assembly: 'Windows.Foundation.UniversalApiContract, Version=14.0.0.0, Culture=neutral, PublicKeyToken=null'

resulting into ERROR *** Instrumentation phase failed 

what can we do as a workaround?

**Comment by SteveGilham** [comment] 2023-06-23 11:51
This will be happening while rewriting instrumented assemblies - `Mono.Cecil` insists on resolving all dependencies during that process, rather than taking the original assembly's references on trust.  The issue seems to be that it isn't detecting the WindowsRT context, and so be expecting `.winmd` assemblies; but I'm not yet sure why.

The workround should be simply to add the `.winmd` file as an explicit dependency 
```
--dependency=[full path to file]
```
or equivalents for `dotnet test` or scripting, and where the full path can include environment variables to expand on the fly.

**Comment by SteveGilham** [comment] 2023-06-28 12:56
Having tried several different combinations of UWP code from [the samples repo](https://github.com/microsoft/Windows-universal-samples/tree/main/Samples), making sure that both contract assemblies are referenced by at least one of the locally built assemblies, I have been unable to repro this issue using the latest release build - the instrumentation process completes, and examining the output assemblies shows it has done the expected code weaving.

This is all using a simple `path\to\AltCover.exe -i path\to\UWP\binaries` command line, no filtering, no dependency declarations.

These all being self-contained examples, the one thing that is lacking is a complicated dependency stack possibly including third-party component libraries also binding to the UWP API contract assemblies - otherwise it all comes down to the mysterious "environmental differences" behind the "works on my machine" effect.

**Comment by 64J0** [comment] 2023-08-08 16:32
In my case, it worked after removing the `/home/redacted/tests/bin` folder entirely.

**Comment by SteveGilham** [comment] 2023-08-08 16:52
`ERROR *** Instrumentation phase failed`
is a generic message; it's the exception information that conveys where the problem lies.

The original issue is one of resolving extended dependencies in UWP assemblies while writing the instrumented assemblies, one that despite having made various attempts to reproduce I have not so far managed to. I'll take this opportunity to was whether @robvdnieuw has a stand-alone minimal repro that could be shared, so the issue could be progressed.

This new report looks like a situation where one of the instrumented assemblies already existed from a previous test run, and whatever was using it has not yet fully released it.  The scorched earth approach of deleting the whole output directory is one way of ensuring that there are no lingering attachments on a file.

**Comment by SteveGilham** [comment] 2024-04-29 07:11
@robvdnieuw Any updates/any simple repro case available? Or shall I close this issue as stale?

**Closed** 2024-05-16 20:01 UTC
Labels: cannot repro
