### ISSUE TITLE
AltCover.Prepare msbuild task throws System.InvalidOperationException when instrumenting some assemblies

### ISSUE THREAD

**Issue by samarunraj** [SteveGilham/altcover#18] opened 2018-05-10 15:25 UTC
Version: altcover.3.0.466.nupkg
```
: error MSB4018: The "AltCover.Prepare" task failed unexpectedly. []
: error MSB4018: System.InvalidOperationException: tried to skip The input sequence has an insufficient number of elements. 1 past the end of the seq []
: error MSB4018:    at Microsoft.FSharp.Collections.SeqModule.Skip@1322.GenerateNext(IEnumerable`1& next) []
: error MSB4018:    at Microsoft.FSharp.Core.CompilerServices.GeneratedSequenceBase`1.MoveNextImpl() []
: error MSB4018:    at Microsoft.FSharp.Collections.Internal.IEnumerator.map@74.DoMoveNext(b& curr) []
: error MSB4018:    at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext() []
: error MSB4018:    at Microsoft.FSharp.Collections.Internal.IEnumerator.next@187[T](FSharpFunc`2 f, IEnumerator`1 e, FSharpRef`1 started, Unit unitVar0) []
: error MSB4018:    at Microsoft.FSharp.Collections.Internal.IEnumerator.filter@182.System-Collections-IEnumerator-MoveNext() []
: error MSB4018:    at Microsoft.FSharp.Collections.Internal.IEnumerator.map@74.DoMoveNext(b& curr) []
: error MSB4018:    at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext() []
: error MSB4018:    at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeOuter@274[T,TResult](ConcatEnumerator`2 x, Unit unitVar0) []
: error MSB4018:    at Microsoft.FSharp.Collections.Internal.IEnumerator.mapi@88.DoMoveNext(b& curr) []
: error MSB4018:    at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext() []
: error MSB4018:    at Microsoft.FSharp.Collections.Internal.IEnumerator.choose@165.System-Collections-IEnumerator-MoveNext() []
: error MSB4018:    at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source) []
: error MSB4018:    at AltCover.Visitor.VisitMethod(MethodDefinition m, Inspect included) in C:\projects\altcover\AltCover\Visitor.fs:line 451 []
: error MSB4018:    at AltCover.Visitor.BuildSequence(Node node) in C:\projects\altcover\AltCover\Visitor.fs:line 497 []
: error MSB4018:    at Microsoft.FSharp.Collections.Internal.IEnumerator.map@74.DoMoveNext(b& curr) []
: error MSB4018:    at Microsoft.FSharp.Collections.Internal.IEnumerator.MapEnumerator`1.System-Collections-IEnumerator-MoveNext() []
: error MSB4018:    at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeOuter@274[T,TResult](ConcatEnumerator`2 x, Unit unitVar0) []
: error MSB4018:    at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeInner@267[T,TResult](ConcatEnumerator`2 x, Unit unitVar0) []
: error MSB4018:    at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeInner@267[T,TResult](ConcatEnumerator`2 x, Unit unitVar0) []
: error MSB4018:    at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeInner@267[T,TResult](ConcatEnumerator`2 x, Unit unitVar0) []
: error MSB4018:    at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeInner@267[T,TResult](ConcatEnumerator`2 x, Unit unitVar0) []
: error MSB4018:    at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeInner@267[T,TResult](ConcatEnumerator`2 x, Unit unitVar0) []
: error MSB4018:    at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeInner@267[T,TResult](ConcatEnumerator`2 x, Unit unitVar0) []
: error MSB4018:    at Microsoft.FSharp.Core.CompilerServices.RuntimeHelpers.takeInner@267[T,TResult](ConcatEnumerator`2 x, Unit unitVar0) []
: error MSB4018:    at Microsoft.FSharp.Collections.SeqModule.Fold[T,TState](FSharpFunc`2 folder, TState state, IEnumerable`1 source) []
: error MSB4018:    at AltCover.Visitor.Visit(FSharpList`1 visitors, IEnumerable`1 assemblies) in C:\projects\altcover\AltCover\Visitor.fs:line 510 []
: error MSB4018:    at AltCover.Main.result@330-4.Invoke(Unit unitVar0) in C:\projects\altcover\AltCover\AltCover.fs:line 344 []
: error MSB4018:    at AltCover.CommandLine.doPathOperation[a](FSharpFunc`2 f, a defaultValue, Boolean store) in C:\projects\altcover\AltCover\CommandLine.fs:line 131 []
: error MSB4018:    at AltCover.Main.DoInstrumentation(String[] arguments) in C:\projects\altcover\AltCover\AltCover.fs:line 330 []
: error MSB4018:    at AltCover.Prepare.Execute() in C:\projects\altcover\AltCover\Tasks.fs:line 50 []
: error MSB4018:    at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() []
: error MSB4018:    at Microsoft.Build.BackEnd.TaskBuilder.<ExecuteInstantiatedTask>d__25.MoveNext() []```

**Comment by SteveGilham** [comment] 2018-05-10 17:01
Only one place that can be.  Fix applied, will be in next release.

**Comment by SteveGilham** [comment] 2018-05-12 07:51
Addressed in release 3.0.475

**Closed by SteveGilham** 2018-05-12 07:51 UTC
Labels: bug, ready to close

**Comment by zarzyckipawel** [comment] 2022-06-14 14:21
I just noticed that I have a similar error on 15 out of 132 test projects. I am using altcover 8.2.837. Any chance you can help me with that? 
`The "AltCover.Prepare" task failed unexpectedly. [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
Mono.Cecil.ResolutionException: Failed to resolve System.Windows.Threading.DispatcherPriority [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at Mono.Cecil.Mixin.CheckedResolve(TypeReference self) [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at Mono.Cecil.MetadataBuilder.GetConstantType(TypeReference constant_type, Object constant) [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at Mono.Cecil.MetadataBuilder.AddConstant(IConstantProvider owner, TypeReference type) [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at Mono.Cecil.MetadataBuilder.AddParameter(UInt16 sequence, ParameterDefinition parameter, ParamTable table) [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at Mono.Cecil.MetadataBuilder.AddParameters(MethodDefinition method) [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at Mono.Cecil.MetadataBuilder.AddMethod(MethodDefinition method) [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at Mono.Cecil.MetadataBuilder.AddMethods(TypeDefinition type) [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at Mono.Cecil.MetadataBuilder.AddType(TypeDefinition type) [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at Mono.Cecil.MetadataBuilder.AddTypes() [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at Mono.Cecil.MetadataBuilder.BuildTypes() [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at Mono.Cecil.MetadataBuilder.BuildModule() [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at Mono.Cecil.MetadataBuilder.BuildMetadata() [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at Mono.Cecil.ModuleWriter.<>c.<BuildMetadata>b__2_0(MetadataBuilder builder, MetadataReader _) [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at Mono.Cecil.ModuleDefinition.Read[TItem,TRet](TItem item, Func`3 read) [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at Mono.Cecil.ModuleWriter.BuildMetadata(ModuleDefinition module, MetadataBuilder metadata) [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at Mono.Cecil.ModuleWriter.Write(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters) [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at Mono.Cecil.ModuleWriter.WriteModule(ModuleDefinition module, Disposable`1 stream, WriterParameters parameters) [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at Mono.Cecil.ModuleDefinition.Write(Stream stream, WriterParameters parameters) [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at Mono.Cecil.AssemblyDefinition.Write(Stream stream, WriterParameters parameters) [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at AltCover.Instrument.I.write@542-1(AssemblyDefinition a, String p, WriterParameters pk) in /_//AltCover.Engine/Instrument.fs:line 546 [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at AltCover.Instrument.I.writeAssembly(AssemblyDefinition assembly, String path) in /_//AltCover.Engine/Instrument.fs:line 553 [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at AltCover.Instrument.I.writeAssemblies(AssemblyDefinition definition, String file, IEnumerable`1 targets, FSharpFunc`2 sink) in /_//AltCover.Engine/Instrument.fs:line 910 [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at AltCover.Instrument.I.visitAfterAssembly(InstrumentContext state, AssemblyEntry assembly) in /_//AltCover.Engine/Instrument.fs:line 1172 [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at AltCover.Instrument.I.instrumentationVisitorWrapper(FSharpFunc`2 core, InstrumentContext state, Node node) in /_//AltCover.Engine/Instrument.fs:line 1514 [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at AltCover.Visitor.stateful@1518-1.Invoke(T node) in /_//AltCover.Engine/Visitor.fs:line 1520 [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at Microsoft.FSharp.Primitives.Basics.List.mapToFreshConsTail[a,b](FSharpList`1 cons, FSharpFunc`2 f, FSharpList`1 x) in D:\a\_work\1\s\src\fsharp\FSharp.Core\local.fs:line 237 [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at Microsoft.FSharp.Primitives.Basics.List.map[T,TResult](FSharpFunc`2 mapping, FSharpList`1 x) in D:\a\_work\1\s\src\fsharp\FSharp.Core\local.fs:line 248 [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at Microsoft.FSharp.Collections.SeqModule.Fold[T,TState](FSharpFunc`2 folder, TState state, IEnumerable`1 source) in D:\a\_work\1\s\src\fsharp\FSharp.Core\seq.fs:line 731 [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at AltCover.Visitor.visit(IEnumerable`1 visitors, IEnumerable`1 assemblies) in /_//AltCover.Engine/Visitor.fs:line 1506 [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at AltCover.Main.I.result@683.Invoke(Unit unitVar0) in /_//AltCover.Engine/Main.fs:line 705 [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at AltCover.CommandLine.I.doPathOperation[a](FSharpFunc`2 f, a defaultValue, Boolean store) in /_//AltCover.Engine/CommandLine.fs:line 248 [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at AltCover.CommandLine.doPathOperation@490.Invoke(FSharpFunc`2 f, a defaultValue, Boolean store) in /_//AltCover.Engine/CommandLine.fs:line 490 [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at AltCover.Main.I.doInstrumentation(String[] arguments) in /_//AltCover.Engine/Main.fs:line 681 [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at AltCover.Main.I.main(String[] arguments) in /_//AltCover.Engine/Main.fs:line 756 [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at AltCover.Main.effectiveMain@762.Invoke(String[] arguments) in /_//AltCover.Engine/Main.fs:line 762 [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at AltCover.Prepare.Execute() in /_//AltCover.Engine/Tasks.fs:line 191 [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at Microsoft.Build.BackEnd.TaskExecutionHost.Microsoft.Build.BackEnd.ITaskExecutionHost.Execute() [C:\GIT\Phoenix\BL\FittingSupport\RemoteAssistanceManager\ComponentTest\RemoteAssistanceManager.ComponentTest.csproj]
   at Microsoft.Build.BackEnd.TaskBuilder.ExecuteInstantiatedTask(ITaskExecutionHost taskExecutionHost, TaskLoggingContext taskLoggingContext, TaskHost taskHost, ItemBucket bucket, TaskExecutionMode howToExecuteTask)`

**Comment by SteveGilham** [comment] 2022-06-14 21:04
This looks more like a variation on issue #20 than anything else -- only this time it's a type resolution rather than an assembly resolution that is failing.  It would be best treated by opening a new issue while I try to reverse engineer the cause.

**Comment by zarzyckipawel** [comment] 2022-06-15 06:42
Thank you for a quick feedback. I created a new issue [156](https://github.com/SteveGilham/altcover/issues/156). While I am still trying to figure out what circumstances are causing this problem to occur.
