### ISSUE TITLE
Attribute order changes when run under AltCover

### ISSUE THREAD

**Issue by jedigo** [SteveGilham/altcover#50] opened 2019-01-11 15:04 UTC
Hi,

We have a test where we are testing Swagger generating descriptions from method attributes.

when we are running this under altcover it seems as though the  attributes are being processed in the reverse order.

Please let me know if this makes sense, or if you need a sample project to demo the issue?

**Comment by SteveGilham** [comment] 2019-01-11 15:42
If you can provide a simple repro that would be an enormous help.

AltCover itself takes a "look, but don't touch" approach to method attributes; but I wonder if the process of re-writing the assembly with Cecil might be causing this.

**Comment by jedigo** [comment] 2019-01-11 15:44
I'll make a minimal repo to demo this.

**Comment by SteveGilham** [comment] 2019-01-11 18:15
Looking at this as a generic problem, it looks like my initial guess was correct -- the Cecil rewriting _is_ inverting the order of method attributes.  A minimal Swagger-based example will still be useful as it seems the most real-world way to surface the issue, both as an AltCover regression test, and as an example for subsequently raising a Cecil issue with.

**Comment by SteveGilham** [comment] 2019-01-12 10:59
If only it were as simple as just reversing the order.  Raised [Cecil issue 558](https://github.com/jbevain/cecil/issues/558) for the underlying problem.

Working around this will be interesting.

**Comment by SteveGilham** [comment] 2019-01-13 10:04
By experiment, reading an assembly with Cecil appears to preserve the attribute order; so it must be the writing out that shuffles the order.

**Comment by SteveGilham** [comment] 2019-01-13 10:49
Down in the depths of Cecil, attributes are put into a data structure that keys them as custom attributes to that method (so each attribute on a given method will get the same key), and then applies [the documented unstable sort](https://docs.microsoft.com/en-us/dotnet/api/system.array.sort?view=netframework-4.7.2#System_Array_Sort_System_Array_System_Int32_System_Int32_System_Collections_IComparer_) `System.Array.Sort (Array array, int index, int length, System.Collections.IComparer comparer);` 

This is not fixable at the consuming application level, I'm afraid.

**Comment by jedigo** [comment] 2019-01-14 14:18
Hi, 
Thanks for the investigation!

I am not sure if it still helpful, but here is a repo with a sample illustrating the issue, based on some actual code implementing swagger generated by attributes: https://github.com/jedigo/SwaggerAttributes

Unfortunately even a minimal example still needs a fairly unwieldy test fixture, but hopefully the actual test case is clear enough.

**Comment by SteveGilham** [comment] 2019-01-31 08:42
The underlying issue is fixed in Cecil with PR565 https://github.com/jbevain/cecil/pull/565
Just awaiting a release containing it.

**Comment by SteveGilham** [comment] 2019-02-01 17:12
AltCover 5.0.665 tales Cecil 0.10.3 which has the fix for this issue.

**Closed** 2019-02-10 13:53 UTC
Labels: Third party, ready to close

**Comment by jedigo** [comment] 2019-02-11 12:14
Hi, I apologise for not getting back to you earlier, but thank you so much for the timely fix!
